SOCIAL_AUTH_TWITTER_KEY = 'GaBMmrgvJBpX1Zhgd2FkyNgQS'
SOCIAL_AUTH_TWITTER_SECRET = 'BkN8ah0Q5tDckPNc7IQYHlG0edZY4J6d6gEMEa7qVVdgLQgHvn'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_URL = '/'
