# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='friend',
            name='favourites_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friend',
            name='followers_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friend',
            name='friends_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friend',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_background_image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='friend',
            name='statuses_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
