# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180404_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('text', models.CharField(default='', max_length=200)),
                ('retweet_count', models.BigIntegerField(default=0)),
                ('retweeted', models.BooleanField(default=True)),
                ('in_reply_to_screen_name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
